config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 root to: 'articles#index'
 resource :timeline, only: [:show]


 resources :articles do
  resources :comments, only: [:new, :create]


  resource :like, only: [:create, :destroy]
end

resources :accounts, only: [:show] do
  resources :follows, only: [:create]
  resources :unfollows, only: [:create]
end

resource :profile, only: [:show, :edit, :update]
resources :favorites, only: [:index]
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_articles_on_user_id  (user_id)
#
class Article < ApplicationRecord
  has_rich_text :content
  has_one_attached :eyecatch

    validates :title, presence: true
    validates :title, length: { minimum: 2, maximum: 100 }
    validates :title, format: { with: /\A(?!\@)/ }

    validates :content, presence: true
    

    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    belongs_to :user

    def display_created_at
        I18n.l(self.created_at, format: :default)
      end

      def author_name
        user.display_name
      end

      def like_count
        likes.count
      end

  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    
    def index
        @articles = Article.all
    end
  

    def show
      
    end

    def new
        @article = current_user.articles.build
    end

    def create
        @article = current_user.articles.build(article_params)
        if @article.save
            redirect_to article_path(@article), notice: '保存できたよ'
        else
            flash.now[:error] = '保存に失敗しました'
            render :new
        end
    end
    
    def edit
     @article = current_user.articles.find(params[:id])
    end

    def update
       @article = current_user.articles.find(params[:id])
        if @article.update(article_params)
            redirect_to article_path(@article), notice: '更新できました'
        else
            flash.now[:error] = '更新できませんでした'
        end
    end

    def destroy
        article = current_user.articles.find(params[:id])
        article.destroy!
        redirect_to root_path, notice: '削除に成功しました'
    end

    private
    def  article_params
        params.require(:article).permit(:title, :content, :eyecatch)
    end

    def set_article
        @article = Article.find(params[:id])
    end
end

app/views/articles/_article.html.haml
= link_to article_path(article) do
  .card
    .card_image
      = image_tag 'eyecatch1.png'
    .card_content
      .card_title
        = article.title
      .card_heart
        = image_tag 'heart.svg'
        %span 23
      .card_detail
        = image_tag 'default-avatar.png'
        %div
          
          %p= article.author_name
          %p= article.display_created_at

app/views/articles/_form.html.haml
.container
  %ul
    - article.errors.full_messages.each do |message|
      %li= message
  = form_with(model: article, local: true) do |f|
    %div
      = f.label :eyecatch, 'アイキャッチ'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.rich_text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/articles/edit.html.haml
= render 'form', article: @article

app/views/articles/index.html.haml
.container
  = render 'tabs'
  - @articles.each do |article|
    = render 'commons/article', article: article
  = link_to new_article_path do
    .float_btn
      %i.fa.fa-plus

app/views/articles/new.html.haml
= render 'form', article: @article

app/views/articles/show.html.haml
.article
  - if @article.eyecatch.attached?
    .article_image
      = image_tag @article.eyecatch
  %h1.article_title= @article.title
  .article_detail
    = link_to account_path(@article.user) do
      = image_tag @article.user.avatar_image
    %div
      %p= @article.author_name
      %p= @article.display_created_at
  - if user_signed_in? && current_user.has_written?(@article)
    .article_detail_actions
      .dropdown
        = image_tag 'actions.svg', class: 'dropbtn'
        .dropdown-content.mini
          = link_to '編集する', edit_article_path(@article)
          = link_to '削除する', article_path(@article), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
.article_content
  = @article.content
- if user_signed_in?
  - if current_user.has_liked?(@article)
    .article_heart
      = link_to article_like_path(@article), data: { method: 'delete' } do
        = image_tag 'heart-active.svg'
  - else
    .article_heart
      = link_to article_like_path(@article), data: { method: 'post' } do
        = image_tag 'heart.svg'