config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 root to: 'articles#index'
 resource :timeline, only: [:show]


 resources :articles do
  resources :comments, only: [:new, :create]


  resource :like, only: [:create, :destroy]
end

resources :accounts, only: [:show] do
  resources :follows, only: [:create]
  resources :unfollows, only: [:create]
end

resource :profile, only: [:show, :edit, :update]
resources :favorites, only: [:index]
end

app/views/commons/_article.html.haml
= link_to article_path(article) do
  .card
    - if article.eyecatch.attached?
      .card_image
        = image_tag article.eyecatch
    .card_content
      .card_title
        = article.title
      .card_heart
        = image_tag 'heart.svg'
        %span= article.like_count
      .card_detail
        = image_tag article.user.avatar_image
        %div
          
          %p= article.author_name
          %p= article.display_created_at

app/views/commons/_articles.html.haml
.container
  = render 'commons/tabs'
  - articles.each do |article|
    = render 'commons/article', article: article
  = link_to new_article_path do
    .float_btn
      %i.fa.fa-plus

app/views/commons/_profile.html.haml
.container.profilePage
  .profilePage_user
    .profilePage_user_image
      = image_tag user.avatar_image
    .profilePage_user_basicInfo
      .profilePage_user_name
        .profilePage_user_displayName
          #{user.display_name}（#{user.age || '？歳'}・#{I18n.t("enum.genders.#{user.gender || 'unknown'}")}）
        .profilePage_user_actionButton
          - if user == current_user
            = link_to 'Edit', edit_profile_path
          - else
            - if current_user&.has_followed?(user)
              = link_to 'Unfollow', account_unfollows_path(user), data: {method: 'post'}
            - else
              = link_to 'Follow', account_follows_path(user), data: {method: 'post'}
      .profilePage_user_introduction
        = user.profile&.introduction

  - user.articles.each do |article|
    = render 'commons/article', article: article

app/views/commons/_tabs.html.haml
.tabs
  .tabs_item{class: "#{add_active_class(root_path)}"}
    = link_to '新着記事一覧', root_path
  .tabs_item{class: "#{add_active_class(timeline_path)}"}
    = link_to 'タイムライン', timeline_path